import type { Metadata } from 'next'
import { CookiesProvider } from 'next-client-cookies/server';
import '@/styles/global.css'
import Navbar from '@/components/Navbar'
import { ToastContainer, toast } from 'react-toastify';

export const metadata: Metadata = {
  title: 'Car auction',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log('layout')
  return (
    <html lang="en">
      <CookiesProvider>
        <body>
          <div className="main">
            <div className="gradient" />
          </div>
          <main className="app">
            <Navbar />
            <ToastContainer />
            {children}
          </main>
        </body>
      </CookiesProvider>
    </html>
  )
}
