import type { Metadata } from 'next'
import { CookiesProvider } from 'next-client-cookies/server';
import '@/styles/global.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <CookiesProvider>
        <body>
          <div className="main">
            <div className="gradient" />
          </div>
          <main className="app">
            {children}
          </main>
        </body>
      </CookiesProvider>
    </html>
  )
}
